kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nvd-driver-custom-bc 
  namespace: gpu-operator-resources
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: >-
        image-registry.openshift-image-registry.svc:5000/gpu-operator-resources/nvd-driver-custom:440.64.00-rhcos4.4
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: DRIVER_VERSION 
          value: 440.64.00
        - name: KERNEL_VERSION 
          value: 4.18.0-147.8.1.el8_1.x86_64
        - name: GCC_VERSION 
          value: 8.3.1
        - name: container
          value: oci
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/spankes/nvd-driver.git'
      ref: master
  triggers: []
  runPolicy: Serial
